stages:
  - build_deploy

build_deploy:
  stage: build_deploy
  environment: production
  before_script:
    - cp $ENV_PRODUCTION .env.docker
  script:
    - docker compose --env-file .env.docker up -d --build
    - docker container prune -f
    - docker image prune -af
    - docker network prune -f
    - docker builder prune --filter unused-for=30m -f
    - docker system df
    - df -h
  only:
    - main
  tags:
    - srv-virtassist01
