version: '3.8'
services:
    chatbot:
        build: ./chatbot
        image: virtassist/chatbot:latest
        container_name: virtassist-chatbot
        command: sh -c "python database.py && python main.py"
        ports:
            - 5000:5000
        env_file:
            - .env.docker
        depends_on:
            - db
            - qa
        networks:
            - chatbot-conn
    db:
        build: ./db
        image: virtassist/db:latest
        container_name: virtassist-db
        ports:
            - 5433:5432
        environment:
            - TZ=${TZ}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - chatbot-conn
    qa:
        build: ./qa
        image: virtassist/qa:latest
        container_name: virtassist-qa
        command: sh -c "cron && python database.py && python main.py"
        ports:
            - 8080:8080
        env_file:
            - .env.docker
        depends_on:
            - db
        networks:
            - chatbot-conn
    admin_panel:
        build: ./admin_panel
        image: virtassist/admin_panel:latest
        container_name: virtassist-admin_panel
        command: gunicorn --bind ${ADMIN_PANEL_HOST} wsgi:app
        ports:
            - 80:80
        env_file:
            - .env.docker
        depends_on:
            - db
            - qa
            - chatbot
        networks:
            - chatbot-conn
volumes:
    db-data:

networks:
    chatbot-conn:
        driver: bridge
